import "./globals.css";
import 'katex/dist/katex.min.css';
import 'highlight.js/styles/github-dark.css'; 

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
